
name: Lint
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      
jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-18.04]
        go-version: [1.13.x, 1.14.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Verify go module dependencies
        run: |
          go mod verify
          go mod download
          
      - name: Run checks
        run: |
          make lint
          exit $STATUS
